# Generated by Django 5.2 on 2025-06-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wbchina', '0004_usertheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTheme',
        ),
    ]
